class JobModel {
  final int id_petugas,id_level_tugas,id_job,id_user,id_group,id_visa,id_bus,operator,id_hotel_madinah,id_hotel_mekah,
      jumlah_tamu,id_airport_datang,id_airport_pulang,koper,tas_jinjing,kursi_roda,id_schedule  ;
  final String status,tugas,nama_user,jenis_kelamin,no_hp,email,no_flight,hari_datang,dep_time_datang,
      arr_time_datang,from_datang,to_datang,no_flight_pulang,hari_pulang,dep_pulang,arr_pulang,from_pulang,to_pulang,
      kd_group,nama_group,kd_visa,nama_visa,kd_transport,nama_transport,kd_airport_datang,nama_airport_datang,kd_airport_pulang,
      nama_airport_pulang,kd_hotel_madinah,hotel_madinah,kd_hotel_mekah,hotel_mekah,ket,type,hari,jam,to_do,driver;
  final DateTime tgl_datang,tgl_pulang,tgl;

  JobModel({this.id_petugas,this.id_level_tugas,this.id_job,this.id_user,this.id_group,this.id_visa,this.id_bus,this.operator,this.id_hotel_madinah,
    this.id_hotel_mekah,this.jumlah_tamu,this.id_airport_datang,this.id_airport_pulang,this.koper,this.tas_jinjing,this.kursi_roda,
    this.id_schedule,this.status,this.tugas,this.nama_user,this.jenis_kelamin,this.no_hp,this.email,this.no_flight,this.hari_datang,
    this.dep_time_datang,this.arr_time_datang,this.from_datang,this.to_datang,this.no_flight_pulang,this.hari_pulang,this.dep_pulang,
    this.arr_pulang,this.from_pulang,this.to_pulang,this.kd_group,this.nama_group,this.kd_visa,this.nama_visa,this.kd_transport,
    this.nama_transport,this.kd_airport_datang,this.nama_airport_datang,this.kd_airport_pulang,this.nama_airport_pulang,
    this.kd_hotel_madinah,this.hotel_madinah,this.kd_hotel_mekah,this.hotel_mekah,this.ket,this.type,this.hari,this.jam,this.to_do,this.driver,
    this.tgl_datang,this.tgl_pulang,this.tgl});

  factory JobModel.fromJson(Map<String, dynamic> data){
    Map parsedJson = data['job'];
    return JobModel(
        id_petugas:parsedJson['id_petugas'],
        id_level_tugas:parsedJson['id_level_tugas'],
        id_job:parsedJson['id_job'],
        id_user:parsedJson['id_user'],
        status:parsedJson['status'],
        tugas:parsedJson['tugas'],
        nama_user:parsedJson['nama_user'],
        jenis_kelamin:parsedJson['jenis_kelamin'],
        no_hp:parsedJson['no_hp'],
        email:parsedJson['email'],
        id_group:parsedJson['id_group'],
        id_visa:parsedJson['id_visa'],
        id_bus:parsedJson['id_bus'],
        operator:parsedJson['operator'],
        id_hotel_madinah:parsedJson['id_hotel_madinah'],
        id_hotel_mekah:parsedJson['id_hotel_mekah'],
        jumlah_tamu:parsedJson['jumlah_tamu'],
        id_airport_datang:parsedJson['id_airport_datang'],
        no_flight:parsedJson['no_flight'],
        tgl_datang:parsedJson['tgl_datang'],
        hari_datang:parsedJson['hari_datang'],
        dep_time_datang:parsedJson['dep_time_datang'],
        arr_time_datang:parsedJson['arr_time_datang'],
        from_datang:parsedJson['from_datang'],
        to_datang:parsedJson['to_datang'],
        id_airport_pulang:parsedJson['id_airport_pulang'],
        no_flight_pulang:parsedJson['no_flight_pulang'],
        hari_pulang:parsedJson['hari_pulang'],
        tgl_pulang:parsedJson['tgl_pulang'],
        dep_pulang:parsedJson['dep_pulang'],
        arr_pulang:parsedJson['arr_pulang'],
        from_pulang:parsedJson['from_pulang'],
        to_pulang:parsedJson['to_pulang'],
        koper:parsedJson['koper'],
        tas_jinjing:parsedJson['tas_jinjing'],
        kursi_roda:parsedJson['kursi_roda'],
        kd_group:parsedJson['kd_group'],
        nama_group:parsedJson['nama_group'],
        kd_visa:parsedJson['kd_visa'],
        nama_visa:parsedJson['nama_visa'],
        kd_transport:parsedJson['kd_transport'],
        nama_transport:parsedJson['nama_transport'],
        kd_airport_datang:parsedJson['kd_airport_datang'],
        nama_airport_datang:parsedJson['nama_airport_datang'],
        kd_airport_pulang:parsedJson['kd_airport_pulang'],
        nama_airport_pulang:parsedJson['nama_airport_pulang'],
        kd_hotel_madinah:parsedJson['kd_hotel_madinah'],
        hotel_madinah:parsedJson['hotel_madinah'],
        kd_hotel_mekah:parsedJson['kd_hotel_mekah'],
        hotel_mekah:parsedJson['hotel_mekah'],
        ket:parsedJson['ket'],
        type:parsedJson['type'],
        hari:parsedJson['hari'],
        tgl:parsedJson['tgl'],
        jam:parsedJson['jam'],
        to_do:parsedJson['to_do'],
        id_schedule:parsedJson['id_schedule'],
        driver:parsedJson['driver']
    );
  }
}